apiVersion: apps/v1
kind: Deployment
metadata:
  name: boston-celtics-store
  labels:
    app: boston-celtics-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boston-celtics-store
  template:
    metadata:
      labels:
        app: boston-celtics-store
    spec:
      containers:
      - name: php
        image: quay.io/andreimititelu/php:1.0.4
        ports:
        - containerPort: 8080
      - name: mariadb
        image: quay.io/andreimititelu/mariadb:1.0.3
        ports:
        - containerPort: 3306
